#pragma config(Motor,  port2,           frontLeft,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontRight,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           backLeft,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backRight ,        tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int x)
{
		motor[port2] = x;
		motor[port3] = x;
		if(x > 0){motor[port4] = x + 20;}else{motor[port4] = x - 20;}
		motor[port5] = x;
}

void dance()
{
	drive(50);
	wait1Msec(1000);
	drive(-50);
	wait1Msec(1000);
	motor[port2] = -80;
	motor[port3] = 80;
	motor[port4] = -80;
	motor[port5] = 80;
	wait1Msec(2000);
	motor[port2] = 80;
	motor[port3] = -80;
	motor[port4] = 80;
	motor[port5] = -80;
	wait1Msec(2000);
}

task main()
{
	while(1 == 1)
	{
		if(vexRT[Btn8U] == 1) // Fowards
		{
			motor[port2] = 50; //50
			motor[port3] = 50; //62
			motor[port4] = 70;
			motor[port5] = 50; //-50
		}
		else if(vexRT[Btn8L]) // Left
		{
			motor[port2] = -80;
			motor[port3] = 80;
			motor[port4] = -80;
			motor[port5] = 80;
		}
		else if(vexRT[Btn8R]) // Right
		{
			motor[port2] = 80;
			motor[port3] = -80;
			motor[port4] = 80;
			motor[port5] = -80;
		}
		else if(vexRT[Btn8D]) // Backwards
		{
			motor[port2] = -50;
			motor[port3] = -50;
			motor[port4] = -70;
			motor[port5] = -50;
		}
		else if(vexRT[Btn7U])
		{
			dance();
		}
		else{
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port4] = 0;
			motor[port5] = 0;
		}
	}
}
