#pragma config(Motor,  port2,           left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right,         tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1){
		if(vexRT[Btn8U] == 1){
			motor[port2] = 50;
			motor[port3] = 50;
		}
		else{
			motor[port2] = 0;
			motor[port3] = 0;
		}
	}


}
